"use client";

import { useState } from "react";
import { ArrowDown, ArrowUpRight, Github, Linkedin, Mail, Server, BrainCircuit, PanelsTopLeft, Database, Smartphone, Code2 } from "lucide-react";
import { motion } from "framer-motion";

const techGroups = [
  { title:"Backend", items:["Java","Spring Boot","Node.js","FastAPI","REST APIs"] },
  { title:"AI / ML", items:["Python","YOLO","Computer Vision","AI APIs"] },
  { title:"Mobile / Frontend", items:["Flutter","React Native","TypeScript","JavaScript","HTML","CSS"] },
  { title:"Data & Infrastructure", items:["PostgreSQL","MongoDB","MySQL","Docker","Firebase","Git","GitHub","Postman"] },
];

const copy = {
 en:{nav:["Work","About","Stack","Experience"],role:"Software Engineer",focus:"AI / ML  ·  BACKEND  ·  FULL-STACK",intro:"I build production-oriented applications with a focus on backend engineering, AI/ML integration and end-to-end product development.",work:"Explore my work",contact:"Contact",status:"OPEN TO SOFTWARE ENGINEERING ROLES",location:"İzmir, Türkiye · Open to relocation",scroll:"SCROLL TO EXPLORE",about:"ABOUT / FOCUS",aboutTitle:"I like building the part behind the interface.",aboutText:"Software Engineer focused on backend-heavy full-stack development, AI/ML integration and production-oriented applications.",stack:"TECHNOLOGY STACK",stackTitle:"Tools I use to turn ideas into working systems.",exp:"EXPERIENCE / EDUCATION"},
 tr:{nav:["Projeler","Hakkımda","Teknolojiler","Deneyim"],role:"Yazılım Mühendisi",focus:"AI / ML  ·  BACKEND  ·  FULL-STACK",intro:"Backend mühendisliği, AI/ML entegrasyonu ve uçtan uca ürün geliştirmeye odaklanan uygulamalar geliştiriyorum.",work:"Projelerimi incele",contact:"İletişim",status:"YAZILIM MÜHENDİSLİĞİ FIRSATLARINA AÇIK",location:"İzmir, Türkiye · Taşınmaya açık",scroll:"KEŞFETMEK İÇİN KAYDIR",about:"HAKKIMDA / ODAK",aboutTitle:"Arayüzün arkasındaki sistemi geliştirmeyi seviyorum.",aboutText:"Backend ağırlıklı full-stack geliştirme, AI/ML entegrasyonu ve üretime yönelik uygulamalara odaklanan bir Yazılım Mühendisiyim.",stack:"TEKNOLOJİLER",stackTitle:"Fikirleri çalışan sistemlere dönüştürürken kullandığım teknolojiler.",exp:"DENEYİM / EĞİTİM"}
};

const focusCards=[
 {icon:Server,title:"Backend Engineering",text:"REST APIs · Authentication · Databases · System Architecture · Docker"},
 {icon:BrainCircuit,title:"AI / ML",text:"Computer Vision · YOLO · AI integrations · Model APIs · Python / FastAPI"},
 {icon:PanelsTopLeft,title:"Product Development",text:"Flutter · React Native · Full-stack systems · Mobile apps · Deployment"}
];

export default function Home(){
 const [lang,setLang]=useState<"en"|"tr">("en"); const t=copy[lang]; const anchors=["#work","#about","#stack","#experience"];
 return <main className="shell">
  <div className="ambient"/>
  <nav className="nav"><a className="mark" href="#top">GE<span>.</span></a><div className="navLinks">{t.nav.map((x,i)=><a href={anchors[i]} key={x}>{x}</a>)}</div><div className="navRight"><a aria-label="GitHub" href="https://github.com/GorkemErtas" target="_blank"><Github size={18}/></a><a aria-label="LinkedIn" href="https://www.linkedin.com/in/gorkem-ertas/" target="_blank"><Linkedin size={18}/></a><button className="lang" onClick={()=>setLang(lang==="en"?"tr":"en")}><b>{lang.toUpperCase()}</b><span>/</span>{lang==="en"?"TR":"EN"}</button></div></nav>
  <section id="top" className="hero">
   <motion.div className="heroCopy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}}><div className="eyebrow"><span>01</span>{t.role}</div><h1><span>GÖRKEM</span><span className="outline">ERTAŞ</span></h1><div className="focus">{t.focus}</div><p className="intro">{t.intro}</p><div className="actions"><a className="primary" href="#work">{t.work}<ArrowDown size={17}/></a><a className="secondary" href="mailto:gorkemertas2002@hotmail.com">{t.contact}<Mail size={17}/></a></div></motion.div>
   <div className="heroAside" aria-hidden="true"><span>BUILD</span><span>CONNECT</span><span>SHIP</span><div>BACKEND / AI / MOBILE</div></div>
   <div className="availability"><i/><div><strong>{t.status}</strong><span>{t.location}</span></div></div><a className="scroll" href="#work">{t.scroll}<ArrowDown size={15}/></a>
  </section>

  <section id="work" className="section work"><div className="sectionLabel"><span>02</span>SELECTED WORK</div><div className="sectionHead"><h2>Building intelligent systems<br/>from backend to interface.</h2><p>Selected projects where I designed and connected the backend, data, AI and mobile layers.</p></div>
   <article className="projectCard eksperCard"><div className="projectInfo"><span className="projectType">PERSONAL PROJECT · FEATURED · GOOGLE PLAY CLOSED TESTING</span><h3>EksperSiz</h3><p>AI-powered Android vehicle inspection and management application. It analyzes vehicle photos with computer vision, matches detected damage to affected parts, and generates AI-assisted inspection reports with repair recommendations and location-aware cost estimates.</p><div className="projectHighlights"><span>AI vehicle inspection</span><span>Vehicle & maintenance tracking</span><span>Nearby automotive services</span><span>Business accounts & shared vehicles</span><span>Freemium billing & report credits</span><span>PDF reports & notifications</span></div><div className="tags">{["Flutter","Dart","Java 21","Spring Boot","Spring Security","PostgreSQL","FastAPI","Python","YOLO","PyTorch","Gemini API","Firebase FCM","RevenueCat","Google Maps & Places","Brevo","Docker","Railway"].map(x=><span key={x}>{x}</span>)}</div><a href="https://github.com/GorkemErtas/ekspersiz" target="_blank">View repository <ArrowUpRight size={16}/></a></div><div className="architecture"><div className="archTitle">PRODUCTION ARCHITECTURE</div><div className="archRow"><div><Smartphone/>Flutter<small>Android App</small></div><b>→</b><div><Server/>Spring Boot<small>REST API · Security · Business Logic</small></div><b>→</b><div><Database/>PostgreSQL<small>Application Data</small></div></div><div className="archServices"><div><BrainCircuit/>FastAPI + YOLO<small>Computer Vision</small></div><div><Code2/>Gemini<small>Inspection Reports</small></div><div><Code2/>External Services<small>Maps · FCM · Billing · Email</small></div></div><div className="pipeline"><strong>AI PIPELINE</strong><span>Photo → Validation → Vehicle → Damage → Part → Matching → ML Result → Gemini Report</span></div></div></article>
   <article className="projectCard projectSecondary"><div className="projectInfo"><span className="projectType">UNIVERSITY CAPSTONE · 4-PERSON TEAM · FULL-STACK CONTRIBUTOR</span><h3>Investing Hub</h3><p>A cross-platform investment and learning platform built as a four-person university capstone. It combines live crypto-market tracking, portfolio management and trade simulation with educational content, price alerts, push notifications and ML-powered short-term price predictions.</p><div className="contribution"><strong>MY CONTRIBUTION</strong><p>Full-stack development across the React Native / Expo client and Node.js backend, with a stronger focus on backend engineering, API integration, authentication and data flows.</p></div><div className="tags">{["React Native","Expo","TypeScript","Node.js","Express","MongoDB","JWT","Firebase FCM","ONNX Runtime","Docker","REST APIs"].map(x=><span key={x}>{x}</span>)}</div><a href="https://github.com/GorkemErtas/Investing-Hub" target="_blank">View repository <ArrowUpRight size={16}/></a></div><div className="architecture"><div className="archTitle">CROSS-PLATFORM SYSTEM</div><div className="archRow"><div><Smartphone/>React Native + Expo<small>Mobile / Web</small></div><b>→</b><div><Server/>Node / Express<small>REST API · Auth</small></div><b>→</b><div><Database/>MongoDB<small>Users · Portfolio</small></div></div><div className="archBranch">↘ <div><BrainCircuit/>ONNX Models<small>Price Prediction</small></div><div><Code2/>Market APIs + FCM<small>Live Data · Alerts</small></div></div></div></article>
  </section>

  <section id="about" className="section"><div className="sectionLabel"><span>03</span>{t.about}</div><div className="aboutGrid"><div><h2>{t.aboutTitle}</h2><p className="lead">{t.aboutText}</p></div><div className="focusGrid">{focusCards.map(({icon:Icon,title,text},i)=><motion.div className="focusCard" key={title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><Icon size={23}/><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></motion.div>)}</div></div></section>

  <section id="stack" className="section stackSection"><div className="sectionLabel"><span>04</span>{t.stack}</div><div className="sectionHead"><h2>{t.stackTitle}</h2></div><div className="stackGrid">{techGroups.map((g,i)=><div className="stackGroup" key={g.title}><span>0{i+1}</span><h3>{g.title}</h3><div>{g.items.map(x=><em key={x}>{x}</em>)}</div></div>)}</div><div className="stackNote"><Code2 size={17}/> No arbitrary skill percentages — technologies are grouped by where I use them.</div></section>

  <section id="experience" className="section experience"><div className="sectionLabel"><span>05</span>{t.exp}</div><div className="timeline"><div className="timelineItem"><span>2024</span><div><h3>IT Intern · GDZ Elektrik Dağıtım A.Ş.</h3><p>IT support analysis, operations and documentation; exposure to corporate infrastructure and software processes.</p></div></div><div className="timelineItem"><span>2020 — 2025</span><div><h3>B.Sc. Software Engineering · Yaşar University</h3><p>Full scholarship.</p></div></div></div></section>
  <footer><span>GÖRKEM ERTAŞ · SOFTWARE ENGINEER</span><a href="mailto:gorkemertas2002@hotmail.com">gorkemertas2002@hotmail.com <ArrowUpRight size={14}/></a></footer>
 </main>
}