export type Language = "tr" | "en";

export const copy = {
 tr:{metaTitle:"Görkem Ertaş | Yazılım Mühendisi",metaDescription:"Yapay zekâ, backend mühendisliği ve full-stack ürün geliştirmeye odaklanan yazılım mühendisi.",nav:["Hakkımda","Projeler","Teknolojiler","Deneyim","İletişim"],role:"Yazılım Mühendisi",focus:"FULL-STACK  ·  AI / ML  ·  MOBİL",intro:"Backend mühendisliği, yapay zekâ entegrasyonu ve uçtan uca ürün geliştirmeye odaklanan, gerçek dünyaya yönelik uygulamalar geliştiriyorum.",work:"Projelerimi keşfet",contact:"İletişim",status:"YAZILIM MÜHENDİSLİĞİ FIRSATLARINA AÇIK",location:"İzmir, Türkiye · Taşınmaya açık",scroll:"KEŞFETMEK İÇİN KAYDIR",about:"HAKKIMDA / ODAK",aboutTitle:"Arayüzün arkasındaki sistemi kurmayı seviyorum.",aboutText:"Backend ağırlıklı full-stack geliştirme, yapay zekâ entegrasyonu ve üretime hazır uygulamalara odaklanan bir yazılım mühendisiyim. Şu anda Generative AI, LLM ve RAG teknolojileri üzerine yoğunlaşıyorum.",stack:"TEKNOLOJİLER",stackTitle:"Fikirleri çalışan sistemlere dönüştürmek için kullandıklarım.",exp:"DENEYİM / EĞİTİM",selected:"ÖNE ÇIKAN PROJELER",workTitle:"Backend'den arayüze akıllı sistemler geliştiriyorum.",workText:"Backend, veri, yapay zekâ ve mobil katmanlarını bir araya getirdiğim seçili projeler.",contactKicker:"06 / İLETİŞİM",contactTitle:"Bir sonraki projeyi birlikte geliştirelim.",contactText:"Backend, yapay zekâ ve full-stack ürün geliştirme alanlarında katkı sunabileceğim yazılım mühendisliği fırsatlarına açığım.",email:"E-posta",locationFooter:"İZMİR, TÜRKİYE · TAŞINMAYA AÇIK"},
 en:{metaTitle:"Görkem Ertaş | Software Engineer",metaDescription:"Software Engineer focused on AI/ML, backend engineering and full-stack product development.",nav:["About","Projects","Stack","Experience","Contact"],role:"Software Engineer",focus:"FULL-STACK  ·  AI / ML  ·  MOBILE",intro:"I build production-oriented applications with a focus on backend engineering, AI/ML integration and end-to-end product development.",work:"Explore my projects",contact:"Contact",status:"OPEN TO SOFTWARE ENGINEERING ROLES",location:"İzmir, Türkiye · Open to relocation",scroll:"SCROLL TO EXPLORE",about:"ABOUT / FOCUS",aboutTitle:"I like building the part behind the interface.",aboutText:"Software Engineer focused on backend-heavy full-stack development, AI/ML integration and production-oriented applications. Currently focusing on Generative AI, LLMs and RAG.",stack:"TECHNOLOGY STACK",stackTitle:"Tools I use to turn ideas into working systems.",exp:"EXPERIENCE / EDUCATION",selected:"SELECTED PROJECTS",workTitle:"Building intelligent systems from backend to interface.",workText:"Selected projects where I designed and connected the backend, data, AI and mobile layers.",contactKicker:"06 / CONTACT",contactTitle:"Let's build what's next.",contactText:"I'm open to Software Engineering opportunities where I can contribute across backend, AI/ML and full-stack product development.",email:"Email",locationFooter:"İZMİR, TÜRKİYE · OPEN TO RELOCATION"}
} as const;

export const details = {
 tr: {
  techGroups: ["Backend","Yapay Zekâ / Makine Öğrenmesi","Mobil / Frontend","Veri ve Altyapı","Geliştirme Araçları"],
  techItems: [["Java","Spring Boot","Node.js","FastAPI","REST API’ler"],["Python","YOLO","Bilgisayarlı görü","RAG","LLM API’leri"],["Flutter","React Native","TypeScript","JavaScript","HTML","CSS"],["PostgreSQL","MongoDB","MySQL","Docker","Firebase","Railway"],["Git","GitHub","Postman","n8n","Jira","Confluence","Claude","Codex"]],
  projectHighlights: [["Yapay zekâ destekli araç incelemesi","Araç ve bakım takibi","Yakındaki otomotiv hizmetleri","İşletme hesapları ve ortak araçlar","Freemium ücretlendirme ve rapor hakları","Tamamlanmış hasar kayıtları ve PDF dışa aktarımı","RAG tabanlı araç asistanı","Bildirimler ve inceleme hatırlatmaları"],["Potansiyel müşteri ve satış takibi","Otomatik raporlama","Örnek kârlılık ve yatırım getirisi analizi","Etkileşimli kontrol paneli"]],
  timeline: {internTitle:"BT Stajyeri · GDZ Elektrik Dağıtım A.Ş.",intern:"BT desteği, operasyon ve dokümantasyon süreçlerinde görev aldım; kurumsal altyapı ve yazılım süreçleri hakkında deneyim kazandım.",degreeTitle:"Yazılım Mühendisliği Lisans Programı · Yaşar Üniversitesi",degree:"Tam burslu.",present:"GÜNÜMÜZ"},
  stackNote:"Keyfî beceri yüzdeleri kullanmıyorum; teknolojileri hangi alanlarda kullandığıma göre grupluyorum.",
  architectureExtra:{leadTitle:"OTOMASYON AKIŞI",webhooks:"Simüle edilmiş müşteri adayı webhookları",leadStats:"Potansiyel müşteriler · Satışlar · Analitik",appData:"Uygulama verileri",roi:"Dönüşüm · Kâr · Yatırım getirisi",leadReporting:"RAPORLAMA VE İÇGÖRÜLER",sheets:"Otomatik raporlar",dashboard:"Canlı kontrol paneli",demoTitle:"DEMO VERİLERİ",demoText:"Simüle edilmiş potansiyel müşteri ve sentetik satış verileri kullanılır; canlı Meta Ads bağlantısı yoktur.",investingTitle:"SİSTEM MİMARİSİ",mobileClient:"Mobil / Web istemcisi",restApi:"REST API · Kimlik doğrulama · Uygulama mantığı",portfolioData:"Kullanıcılar · Portföy verileri",integrations:"BACKEND ENTEGRASYONLARI",mlPrediction:"Makine öğrenmesiyle fiyat tahmini",marketData:"Canlı piyasa verileri · Uyarılar"},
  focusCards: [
   { title:"Backend Mühendisliği", text:"REST API'ler · Kimlik doğrulama · Veritabanları · Sistem mimarisi · Docker" },
   { title:"Yapay Zekâ / Makine Öğrenmesi", text:"Bilgisayarlı görü · YOLO · Yapay zekâ entegrasyonları · Model API'leri · Python / FastAPI" },
   { title:"Ürün Geliştirme", text:"Flutter · React Native · Full-stack sistemler · Mobil uygulamalar · Dağıtım" }
  ],
  slides: [
   { eyebrow:"YAPAY ZEKÂLI ARAÇ ASİSTANI", title:"Aracınızı tek bir panelden yönetin.", text:"Hasar analizi başlatın, aracınızı takip edin ve bakım bilgilerine tek bir yerden ulaşın." },
   { eyebrow:"YAPAY ZEKÂLI ARAÇ ASİSTANI", title:"Aracınız hakkında sorular sorun.", text:"Güvenilir bilgi kaynaklarını ve erişim yetkisi bulunan araç verilerini kullanan RAG tabanlı asistandan otomotiv desteği alın." },
   { eyebrow:"ARAÇ TAKİBİ", title:"Bakım kayıtları ve hatırlatmalar bir arada.", text:"Bakım geçmişini, yaklaşan hatırlatmaları ve araçtaki son görünür hasar durumunu takip edin." },
   { eyebrow:"ANALİZ GEÇMİŞİ", title:"Tamamlanan incelemeler her zaman elinizin altında.", text:"Önceki hasar analizlerini inceleyin ve yapay zekâ tarafından oluşturulan raporları tek bir geçmiş ekranından açın." },
   { eyebrow:"BİLGİSAYARLI GÖRÜ", title:"Araç fotoğraflarından yapılandırılmış hasar bilgisi elde edin.", text:"Analiz akışı görünür hasarları tespit eder; hasar şiddetini, etkilenen parçaları ve model güven skorunu sunar." },
   { eyebrow:"YAPAY ZEKÂ RAPORLAMA", title:"Hasar tespitinden uygulanabilir inceleme raporuna.", text:"Yapay zekâ destekli raporlar hasarı, onarım önerilerini ve tahmini onarım maliyetine ilişkin bilgileri özetler." }
  ],
  projectMeta: ["KİŞİSEL PROJE","ÖNE ÇIKAN","GOOGLE PLAY KAPALI TEST","ÜNİVERSİTE BİTİRME PROJESİ","4 KİŞİLİK EKİP","FULL-STACK GELİŞTİRİCİ","CANLI DEMO"],
  eksperDescription:"Araç yönetimi ve yapay zekâ destekli hasar incelemesi için geliştirilmiş bir Android uygulaması. Bilgisayarlı görü ile görünür hasarları belirler; bakım takibi, işletme hesapları ve tamamlanmış PDF hasar kayıtları sunar. Ayrıca bilgi erişimi ve yetkilendirilmiş araç verilerine güvenli erişim sağlayan RAG tabanlı bir araç asistanı içerir.",
  leadDescription:"Potansiyel müşterilerin sisteme girişinden satışa dönüşümüne kadar süreci izleyen; reklam maliyetleri, gelir ve kârlılık arasındaki ilişkiyi gösteren çalışan bir satış otomasyonu demosu. Etkileşimli panel üzerinden raporlama akışını deneyebilirsiniz.",
  investingDescription:"Dört kişilik üniversite bitirme ekibiyle geliştirilen platformlar arası yatırım ve öğrenme uygulaması. Canlı kripto piyasası takibi, portföy yönetimi ve işlem simülasyonunu; eğitim içerikleri, fiyat uyarıları, anlık bildirimler ve makine öğrenmesi destekli kısa vadeli fiyat tahminleriyle birleştirir.",
  contribution:"React Native / Expo istemcisi ve Node.js backend üzerinde full-stack geliştirme yaptım; özellikle backend geliştirme, API entegrasyonu, kimlik doğrulama ve veri akışlarına odaklandım.",
  system:"SİSTEM MİMARİSİ", backendIntegrations:"BACKEND ENTEGRASYONLARI", aiFlow:"YAPAY ZEKÂ İŞLEME AKIŞI", assistantFlow:"YAPAY ZEKÂ ASİSTANI · RAG + GÜVENLİ ARAÇLAR",
  architecture: ["Android istemcisi","REST API · Kimlik doğrulama · İş mantığı","Uygulama verileri · Vektör arama","Araç ve hasar tespiti","Yapay zekâ raporları · Asistan","Haritalar · FCM · RevenueCat · Brevo"],
  pipelines:["Fotoğraf → Doğrulama → Araç tespiti → Hasar tespiti → Parça eşleştirme → Yapay zekâ raporu","Soru → Niyet ve kapsam → RAG erişimi / Yetkili araçlar → Kanıta dayalı yanıt"],
  labels:{source:"Kaynak kod",dashboard:"Paneli dene",comingSoon:"Yakında",liveDemo:"CANLI DEMO",present:"GÜNÜMÜZ",googlePlay:"GOOGLE PLAY",github:"GITHUB",sourceCode:"Kaynak kod",preview:"UYGULAMA ÖNİZLEMESİ",systemDesign:"SİSTEM TASARIMI",previous:"Önceki ekran görüntüsü",next:"Sonraki ekran görüntüsü",myContribution:"KATKIM",personalProject:"KİŞİSEL PROJE",university:"ÜNİVERSİTE BİTİRME PROJESİ",team:"4 KİŞİLİK EKİP",fullStack:"FULL-STACK GELİŞTİRİCİ",liveDemo:"CANLI DEMO",closedTesting:"GOOGLE PLAY KAPALI TEST"}
 },
 en: {
  techGroups: ["Backend","AI / ML","Mobile / Frontend","Data & Infrastructure","Development Tools"],
  techItems: [["Java","Spring Boot","Node.js","FastAPI","REST APIs"],["Python","YOLO","Computer Vision","RAG","LLM APIs"],["Flutter","React Native","TypeScript","JavaScript","HTML","CSS"],["PostgreSQL","MongoDB","MySQL","Docker","Firebase","Railway"],["Git","GitHub","Postman","n8n","Jira","Confluence","Claude","Codex"]],
  projectHighlights: [["AI vehicle inspection","Vehicle and maintenance tracking","Nearby automotive services","Business accounts and shared vehicles","Freemium billing and report credits","Finalized damage records and PDF export","RAG-powered vehicle assistant","Notifications and inspection reminders"],["Lead intake and sales tracking","Automated reporting","Illustrative profitability and ROI","Interactive dashboard"]],
  timeline: {internTitle:"IT Intern · GDZ Elektrik Dağıtım A.Ş.",intern:"Supported IT operations, analysis and documentation, gaining exposure to corporate infrastructure and software processes.",degreeTitle:"B.Sc. Software Engineering · Yaşar University",degree:"Full scholarship.",present:"PRESENT"},
  stackNote:"No arbitrary skill percentages — technologies are grouped by where I use them.",
  architectureExtra:{leadTitle:"AUTOMATION FLOW",webhooks:"Simulated lead webhooks",leadStats:"Leads · Sales · Analytics",appData:"Application data",roi:"Conversion · Profit · ROI",leadReporting:"REPORTING & INSIGHTS",sheets:"Automated reports",dashboard:"Live dashboard",demoTitle:"DEMO DATA",demoText:"Uses simulated leads and synthetic sales data; there is no live Meta Ads connection.",investingTitle:"SYSTEM ARCHITECTURE",mobileClient:"Mobile / Web Client",restApi:"REST API · Authentication · Application Logic",portfolioData:"Users · Portfolio Data",integrations:"BACKEND INTEGRATIONS",mlPrediction:"ML Price Prediction",marketData:"Live Market Data · Alerts"},
  focusCards: [
   { title:"Backend Engineering", text:"REST APIs · Authentication · Databases · System Architecture · Docker" },
   { title:"AI / ML", text:"Computer Vision · YOLO · AI integrations · Model APIs · Python / FastAPI" },
   { title:"Product Development", text:"Flutter · React Native · Full-stack systems · Mobile apps · Deployment" }
  ],
  slides: [
   { eyebrow:"AI VEHICLE ASSISTANT", title:"Manage your vehicle from one dashboard.", text:"Start a damage analysis, track your vehicle and access maintenance information in one place." },
   { eyebrow:"AI VEHICLE ASSISTANT", title:"Ask questions about your vehicle.", text:"Get automotive guidance from a RAG-powered assistant grounded in trusted knowledge and vehicle data you are authorized to access." },
   { eyebrow:"VEHICLE TRACKING", title:"Maintenance and reminders, all in one place.", text:"Keep track of maintenance history, upcoming reminders and the vehicle's latest recorded visible-damage status." },
   { eyebrow:"ANALYSIS HISTORY", title:"Completed inspections, always within reach.", text:"Review previous damage analyses and open AI-generated reports from a single, organized history." },
   { eyebrow:"COMPUTER VISION", title:"Turn vehicle photos into structured damage insights.", text:"The analysis flow detects visible damage and presents severity, affected parts and model confidence scores." },
   { eyebrow:"AI REPORTING", title:"From damage detection to an actionable inspection report.", text:"AI-assisted reports summarize damage, repair recommendations and estimated repair-cost context." }
  ],
  projectMeta: ["PERSONAL PROJECT","FEATURED","GOOGLE PLAY CLOSED TESTING","UNIVERSITY CAPSTONE","4-PERSON TEAM","FULL-STACK CONTRIBUTOR","LIVE DEMO"],
  eksperDescription:"An Android app for vehicle management and AI-assisted damage inspections. It uses computer vision to identify visible damage and provides maintenance tracking, business accounts and finalized PDF damage records. It also includes a RAG-based vehicle assistant with knowledge retrieval and secure access to authorized vehicle data.",
  leadDescription:"A working sales-automation demo that tracks leads from intake through conversion and shows how advertising spend, revenue and profitability relate. Explore the reporting workflow through an interactive dashboard.",
  investingDescription:"A cross-platform investment and learning app built as a four-person university capstone. It combines live crypto-market tracking, portfolio management and trade simulation with educational content, price alerts, push notifications and machine-learning-powered short-term price forecasts.",
  contribution:"I contributed to full-stack development across the React Native / Expo client and Node.js backend, with a stronger focus on backend engineering, API integration, authentication and data flows.",
  system:"SYSTEM ARCHITECTURE", backendIntegrations:"BACKEND INTEGRATIONS", aiFlow:"AI PROCESSING FLOW", assistantFlow:"AI ASSISTANT · RAG + SECURE TOOLS",
  architecture: ["Android Client","REST API · Authentication · Business Logic","App Data · Vector Search","Vehicle & Damage Detection","AI Reports · Assistant","Maps · FCM · RevenueCat · Brevo"],
  pipelines:["Photo → Validation → Vehicle Detection → Damage Detection → Part Matching → AI Report","Question → Intent & Scope → RAG Retrieval / Authorized Tools → Evidence-grounded Answer"],
  labels:{source:"Source code",dashboard:"Try dashboard",comingSoon:"Coming soon",liveDemo:"LIVE DEMO",present:"PRESENT",googlePlay:"GOOGLE PLAY",github:"GITHUB",sourceCode:"Source code",preview:"APP PREVIEW",systemDesign:"SYSTEM DESIGN",previous:"Previous screenshot",next:"Next screenshot",myContribution:"MY CONTRIBUTION",personalProject:"PERSONAL PROJECT",university:"UNIVERSITY CAPSTONE",team:"4-PERSON TEAM",fullStack:"FULL-STACK CONTRIBUTOR",liveDemo:"LIVE DEMO",closedTesting:"GOOGLE PLAY CLOSED TESTING"}
 }
} as const;
